### ISSUE TITLE
shutter width px not working

### ISSUE THREAD

**Issue by Winzy54** [Deejayfool/hass-shutter-card#112]
Hi. 
this looks amazing. i want to put about 5-7 shutters in a row and i try to change the shutter width but as soon as i add the code for it, the image disappear. 
 
```
type: custom:shutter-card
title: Bed Room
entities:
  - entity: cover.bed_room_entrance
    shutter_width_px: 80px
    name: Entrance
    buttons_position: left
  - entity: cover.bed_room_bath
    name: Bath

```

![image](https://github.com/Deejayfool/hass-shutter-card/assets/152816814/94b247d7-0f4a-4284-8846-7b7a346cea6a)

**Comment by d3z1b3l** [comment]
Hi, 
I don't have your problem!
For me it works.
I have this Problem, look at my post: [https://github.com/Deejayfool/hass-shutter-card/issues/114](url)

Here my code, you can try with copy/paste:


```
type: custom:shutter-card
entities:
  - entity: cover.07_speis_rollo
    name: Rollo
    buttons_position: bottom
    title_position: null
    shutter_width_px: 200
    always_percentage: true

```
