### ISSUE TITLE
Enhancement request: step sliding 

### ISSUE THREAD

**Issue by fredericks1982** [Deejayfool/hass-shutter-card#13]
Great work! 😃
To do the same job I was using an [`input_number`](https://www.home-assistant.io/integrations/input_number/) with this configuration: 
``` yaml
awning_group_position:
  name: Awnings
  min: 0
  max: 100
  step: 25
  mode: slider
  unit_of_measurement: '%'
  icon: mdi:pan-horizontal
``` 
It would be great if your custom card would have a `step` parameter, allowing the user to set 'discreet' sliding actions (e.g. only 0% - 25% - 50% - 75% - 100%).
