### ISSUE TITLE
No visual editor available for: custom:shutter-card

### ISSUE THREAD

**Issue by LSousa77** [Deejayfool/hass-shutter-card#16]
Hi.
I need your help please. I have installed that crazy shutter-card via HACS, so everything it's auto configurated.
But, when i try to configure an Shelly 2.5 Shutter control appears that info: **No visual editor available for: custom:shutter-card**

![image](https://user-images.githubusercontent.com/7023030/86621147-95b6ea80-bfb5-11ea-891c-c3a78bb84455.png)

What i'm doing wrong?
That's also normal the "custom:shutter-card" appears on red?

Thanks in advance

deSousa

**Comment by Deejayfool** [comment]
Hello,
Everything is correct. "custom:shutter-card" is in red because it's a string between quotes. It's just syntax coloration, but nothing to do with an error.
And like almost all custom cards, there is no visual editor, that's why you need to configure the card by writing yaml, and that's what you did. So one more time, everything is correct :) .

**Comment by LSousa77** [comment]
So why i change buttons_position: right and title_position: top and there's no change and i also can't do any change on shutter. i put on 100% close or 50% open but no changes on shutter

**Comment by Deejayfool** [comment]
Normally if you choose "buttons_position: right", it should be correct. Maybe you need to click on "Save" to see the update.
If you choose a percentage and your shutter doesn't move, it's probably that your shutter doesn't work with percentage.
To check it, try in the Developer tool to call the service "cover.set_cover_position" :
![image](https://user-images.githubusercontent.com/708628/86636711-e8ec6580-bfd4-11ea-9c72-337948249c9e.png)

**Comment by LSousa77** [comment]
Hi again
The percentage works but  can't configure the: - buttons position, the name and the title_position...

About the example: 

type: 'custom:shutter-card'
title: My shutters
entities:
- entity: cover.left_living_shutter
name: Left shutter
buttons_position: left
title_position: bottom
- cover.bedroom_shutter


cover.bedroom_shutter refears to a diferent shutter than - entity: cover.left_living_shutter? I can put 2 different shutters on the sabe room?

**Comment by Deejayfool** [comment]
I don't understand the problem with the buttons position, name and title_position. Send me a screenshot of the yaml configuration and of the display result so I can help you more.
Concerning the example, you can add as many shutters as you want. In the example, I display 2 shutters in the same card (left_living_shutter and bedroom_shutter). But you can display just one, or several.

**Comment by LSousa77** [comment]
Hi as you can see on that image the the buttons_position, name and title_position doesn't work the **name:** appears with the Shelly internal name not the selected, the **buttons_position** appears left instead right as i have selected and the **title:** appears on top instead on bottom as i have selected.

![image](https://user-images.githubusercontent.com/7023030/86763119-0229fc00-c03f-11ea-91ac-d35a85c1cb77.png)

I tried to add a new shutter on the end and appears that info

![image](https://user-images.githubusercontent.com/7023030/86764029-aa3fc500-c03f-11ea-8568-8f4eec6667d2.png)

i have give somes spaces and appears accept the code but no extra shutter on the same card

![image](https://user-images.githubusercontent.com/7023030/86764857-51246100-c040-11ea-8ab6-5b3e7158ff93.png)

**Comment by Deejayfool** [comment]
Hello,
Look closer at my example. The spaces are "in front" of the properties "name", "buttons_position" and "title_position". I still don't see them on your screenshots.

**Comment by LSousa77** [comment]
Sorry i don't understand. Can you pick on my code and fix them? Thank's

type: 'custom:shutter-card'
title: Cozinha
entities:
  - entity: cover.shelly_shsw_25_****************
name: Principal
buttons_position: right
title_position: bottom

**Comment by Deejayfool** [comment]
Ok, here is your code:
```
type: 'custom:shutter-card'
title: Cozinha
entities:
  - entity: cover.shelly_shsw_25_****************
name: Principal
buttons_position: right
title_position: bottom
```

And here is the working code:
```
type: 'custom:shutter-card'
title: Cozinha
entities:
  - entity: cover.shelly_shsw_25_****************
    name: Principal
    buttons_position: right
    title_position: bottom
```

**Comment by LSousa77** [comment]
The bottons and title don't changes

**Comment by Deejayfool** [comment]
Click on save to update the card. If it still doesn't work, send me an other screenshot of your configuration so I can help you more.

**Comment by LSousa77** [comment]
Huau it's work's . And to add another shutter? I added anhoter cover as shown 

type: 'custom:shutter-card'
title: Cozinha
entities:
  - entity: cover.shelly_shsw_25_****************
    name: Principal
    buttons_position: right
    title_position: bottom
  - cover.shelly_shsw_25_****************

But to configure the button position?

**Comment by LSousa77** [comment]
How can i write the code so i can configure the second cover?

![image](https://user-images.githubusercontent.com/7023030/86775196-183fb880-c04f-11ea-9083-4f22b84046cd.png)

**Comment by Deejayfool** [comment]
You can just repeat the bloc "entity" as much times as you want.
So you can have:
```yaml
type: 'custom:shutter-card'
title: Cozinha
entities:
  - entity: cover.shelly_shsw_25_****************
    name: Principal
    buttons_position: right
    title_position: bottom
  - entity: cover.shelly_shsw_26_****************
    name: Second
    buttons_position: right
    title_position: bottom
  - entity: cover.shelly_shsw_27_****************
    name: Third
    buttons_position: right
    title_position: bottom
```
