### ISSUE TITLE
Position undefined after HA restart

### ISSUE THREAD

**Issue by ThierryM** [Deejayfool/hass-shutter-card#19]
Hi,
Thanks for your awesome plugin that I'm discovering at the same time with HA.
When HA restart, the shutter position is undefined.
Therefore, I created a automation rule in automations.yaml in order to obtain the shutters positions:
```
#Permet de récupérer la position des volets roulants au redémarrage
- alias: "Power state on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "cmnd/VR_Bureau_IP70/shutterposition"
        payload: ""
```

You can see that this rule works in this picture for a normal card but not in the plugin:
![Sélection_478](https://user-images.githubusercontent.com/1470067/89407741-9d39f280-d71f-11ea-90b8-a34379f35404.png)
Once I move the shutter, the position is actualized and no more problem:
![Sélection_479](https://user-images.githubusercontent.com/1470067/89407809-b9d62a80-d71f-11ea-8ec8-c6b6cc1ded59.png)

So, how can I obtain the shutter position at HA restart ?
Thanks for your help and your sharing,
Regards,

Thierry
