### ISSUE TITLE
Configuration for USB relay controlled shutters?

### ISSUE THREAD

**Issue by stefferber** [Deejayfool/hass-shutter-card#37]
Thx for providing this excellent Home Assistant shutter card. I am using it with two different home assistant integrations for my solar powered [Velux SSL](https://velcdn.azureedge.net/-/media/marketing/products/m/01/de/blinds/sss/142293-01-xxl.jpg) blindes

1. Velux SSL with IO-Homecontrol integrated via [Velux KLF 200 ](https://www.home-assistant.io/integrations/velux/)
2. Velux SSL (old, no IO-Homecontrol) integrated with an [USB relay ](https://info.kmtronic.com/usb-four-channel-relay-controller-pcb.html)to switch the remote control directly [(hardware hack)](https://youtu.be/GDwzwg-93yY)

<img width="588" alt="Bildschirmfoto 2021-01-18 um 21 41 39" src="https://user-images.githubusercontent.com/5459845/104961132-02378b00-59d6-11eb-9864-90c9ffd04f7f.png">

For 1. everything works perfect  but for 2. I cannot use the full `hass-shutter-card` functionallity as my hardware hack does not provide any status information. 

```
type: 'custom:shutter-card'
title: Velux Shutters
entities:
  - entity: cover.markise_dach
    name: VELUX SSL via USB-Relay
    buttons_position: left
    title_position: bottom
```
Here is my `configuration.yaml`:  
```
# Velux KLF 200 for Windows and shades
velux:
  host: 192.168.178.129
  password: <my-velux-klf-password>

# Velux SSL roof shades via relay
cover:
  - platform: command_line
    covers:
      markise_dach:
        command_open: 'echo -e "\xFF\x01\x01" > /dev/ttyUSB0; sleep 0.2; echo -e "\xFF\x01\x00" > /dev/ttyUSB0'
        command_close: 'echo -e "\xFF\x02\x01" > /dev/ttyUSB0; sleep 0.2; echo -e "\xFF\x02\x00" > /dev/ttyUSB0'
```
I know I **did not** implement 
```
        command_stop: ...
        command_state: ...
        value_template: >
          {% if value == 'open' %}
          100
          {% elif value == 'closed' %}
          0
          {% endif %}
```
as I have somehow to fake these commands and status e.g. by counting the seconds the blind typically requires to close. Now my question is: 

What kind of information and status is required in order to make `hass-shutter-card` work?
Do you have similar examples already working?
