### ISSUE TITLE
one card - multiple shutters

### ISSUE THREAD

**Issue by danmckp** [Deejayfool/hass-shutter-card#40]
hello there is possible to manage multiple shutters by one shutter card ? could someone show me configuration ?

**Comment by hsolberg** [comment]
Check out the documentation here: https://www.home-assistant.io/integrations/cover.group/

In short you just need to add the shutters you want to control as "one" to a group. You will then get a new entity that controls all of them.

In configuration.yaml:
````
cover:
  - platform: group
    name: all shutters
    entities:
      - cover.qubino_zmnhod1_flush_shutter_dc_level
      - cover.qubino_zmnhod1_flush_shutter_dc_level_2
````

In lovelace-ui:
````
type: 'custom:shutter-card'
title: All shutters
entities:
  - entity: cover.all_shutters
````
