### ISSUE TITLE
Missing Buttons after update of everything

### ISSUE THREAD

**Issue by opale1981** [Deejayfool/hass-shutter-card#70]
Hello
I've just updated all (HA, HACS and shutter-card) to the last version and I can't see the button anymore. I have a gray circle appearing on hovering
![image](https://user-images.githubusercontent.com/82212962/161052579-d3b26ddc-482b-4f30-9ce0-52110be21142.png)

code is:
```
type: custom:shutter-card
entities:
  - entity: cover.tutte_le_veneziane
    name: Tutte
    buttons_position: left
    invert_percentage: true
```
