### ISSUE TITLE
Direction overlay disables open/close swipe action

### ISSUE THREAD

**Issue by deam0n** [Deejayfool/hass-shutter-card#95]
After one of the last updates of Home Assistant, this card displays an arrow informing the last movement of the shade:

![image](https://user-images.githubusercontent.com/1869650/236877352-d77cbed9-fb63-4315-8df0-2d0a7442c33e.png)

However this disables the normal function of the card when we try to pull the shade up or down.
It's like there's an overlay.

Card Config:
```
type: vertical-stack
cards:
  - type: custom:shutter-card
    entities:
      - entity: cover.shade1
        name: Shade 1
        buttons_position: right
      - entity: cover.shade2
        name: Shade 2
        buttons_position: right
```
